name: ripple
version: 0.5.0
author: Tom Yeh <tomyeh@rikulo.org>
description: Lightweight Dart messaging server; supporting STOMP messaging protocol.
homepage: https://github.com/rikulo/ripple
dependencies:
  meta: any
  logging: any
  rikulo_commons: any
  stomp: any
