name: messa
version: 0.5.0
author: Tom Yeh <tomyeh@rikulo.org>
description: Lightweight Dart messaging server; supporting STOMP messaging protocol.
homepage: https://github.com/rikulo/messa
dependencies:
  meta: any
  stomp: {path: ../stomp}
